language: go
go:
  - 1.13.x
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
git:
  depth: 1
env:
  global:
    - GO111MODULE=on
notifications:
  email: false
before_install:
  - go get github.com/mattn/goveralls
script:
  - go build
  - go test -coverpkg ./... ./...
  - $GOPATH/bin/goveralls -service=travis-ci
